# Generated by Django 3.1.7 on 2021-03-24 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment_timespan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning', models.DateTimeField(verbose_name='beginning')),
                ('end', models.DateTimeField(verbose_name='end')),
                ('max_group_size', models.IntegerField(verbose_name='max_group_size')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='Hairmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last_name')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('phone', models.CharField(max_length=10, verbose_name='phone')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('age', models.IntegerField(verbose_name='age')),
                ('gender', models.CharField(max_length=10, verbose_name='gender')),
                ('hair_length', models.CharField(max_length=20, verbose_name='hair_length')),
                ('hair_procedures', models.CharField(max_length=20, verbose_name='hair_procedures')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50, verbose_name='service_name')),
                ('duration', models.IntegerField(verbose_name='duration')),
                ('price', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='price')),
                ('max_group_size', models.IntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.category', verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last_name')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('phone', models.CharField(max_length=10, verbose_name='phone')),
                ('group_size', models.IntegerField(verbose_name='group_size')),
                ('appointment_date', models.DateTimeField(verbose_name='appointment')),
                ('place', models.CharField(max_length=50, verbose_name='place')),
                ('info', models.CharField(max_length=200, verbose_name='info')),
                ('confirmed', models.BooleanField(verbose_name='confirmed')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.service', verbose_name='service')),
            ],
        ),
    ]
