# Generated by Django 3.1.7 on 2021-03-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='image'),
        ),
    ]
