# Generated by Django 3.1.7 on 2021-04-06 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20210406_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment_timespan', verbose_name='appointment_date'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='place',
            field=models.CharField(default='', max_length=50, verbose_name='place'),
            preserve_default=False,
        ),
    ]
