# Generated by Django 3.1.7 on 2021-04-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_auto_20210426_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairmodel',
            name='gender',
            field=models.CharField(choices=[('FEMALE', 'nainen'), ('MALE', 'mies'), ('OTHER', 'muu/en halua määritellä')], default='OTHER', max_length=50, verbose_name='gender'),
        ),
    ]
