# Generated by Django 3.1.7 on 2021-05-03 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_auto_20210426_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='hairmodel',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='phone'),
        ),
    ]
